[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
postgresql_host = localhost
postgresql_user = gpe
postgresql_password = gpe
postgresql_dbname = gpe