models:
  - name: stg_insee_communes
    description: "Communes IDF avec indicateurs socio-économiques INSEE 2022"
    columns:
      - name: code_commune
        tests:
          - not_null
          - unique

      - name: nom_commune
        tests:
          - not_null:
              config:
                severity: warn

      - name: population
        tests:
          - not_null:
              config:
                severity: warn
